import { pgTable, uuid, varchar, timestamp, pgEnum, decimal, text, integer, boolean, unique } from 'drizzle-orm/pg-core';

export const userRoleEnum = pgEnum('user_role', ['user', 'admin', 'booster']);

export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(),
  username: varchar('username', { length: 50 }).notNull().unique(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  // NULL for accounts created via OAuth (Yandex) that never set a password.
  // Such users can still set one later through the forgot-password flow.
  passwordHash: varchar('password_hash', { length: 255 }),
  role: userRoleEnum('role').default('user'),
  avatarUrl: varchar('avatar_url', { length: 255 }),
  telegramUsername: varchar('telegram_username', { length: 255 }),
  // LEGACY: replaced by adventureRank at checkout/profile. Kept so old users'
  // data stays readable in admin views; no active flow writes it anymore.
  gameUsername: varchar('game_username', { length: 255 }),
  // Ранг приключений (Adventure Rank), 1–60. Will later gate services that
  // require a minimum AR.
  adventureRank: integer('adventure_rank'),
  receiptEmail: varchar('receipt_email', { length: 255 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

// External login identities (OAuth). One user can have several providers
// linked; a (provider, providerAccountId) pair maps to exactly one user.
// Linking by verified provider email happens in lib/oauthUser.ts.
export const oauthAccounts = pgTable('oauth_accounts', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  provider: varchar('provider', { length: 32 }).notNull(), // e.g. 'yandex'
  providerAccountId: varchar('provider_account_id', { length: 255 }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (t) => [
  unique('oauth_accounts_provider_account_unique').on(t.provider, t.providerAccountId),
]);

export const otps = pgTable('otps', {
  email: varchar('email', { length: 255 }).primaryKey(),
  code: varchar('code', { length: 6 }).notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const passwordResetTokens = pgTable('password_reset_tokens', {
  email: varchar('email', { length: 255 }).primaryKey(),
  token: varchar('token', { length: 64 }).notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const categories = pgTable('categories', {
  id: uuid('id').defaultRandom().primaryKey(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  title: varchar('title', { length: 255 }).notNull(),
  description: varchar('description'),
  order: integer('order').default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const services = pgTable('services', {
  id: uuid('id').defaultRandom().primaryKey(),
  categoryId: uuid('category_id').references(() => categories.id, { onDelete: 'cascade' }),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  title: varchar('title', { length: 255 }).notNull(),
  subtitle: varchar('subtitle', { length: 255 }),
  description: varchar('description'),
  price: varchar('price', { length: 20 }).notNull(), // Decimal stored as string
  imageUrl: varchar('image_url', { length: 255 }),
  // How the catalogue card should frame `imageUrl`. NULL (the default) fills the
  // box and crops — right for a screenshot. 'contain' shows the picture whole on
  // a blurred copy of itself, for artwork that cropping destroys: square item
  // icons on a flat background, where the box's edges cut straight through the
  // icon. Set by `scripts/covers/flag-icon-artwork.mjs`.
  imageFit: varchar('image_fit', { length: 10 }),
  // Genshin region a quest belongs to, e.g. 'natlan' (see lib/questRegions.json).
  // Resolved once from `service_addons` (a quest is linked to the exploration
  // service it gates) and stored, so unlinking an addon later cannot silently
  // change the artwork. Quests have no artwork of their own: `imageUrl` holds a
  // region tile generated by `scripts/covers/build-quest-covers.mjs`, and the
  // catalogue card uses this key to draw a typographic cover live
  // (`components/QuestCover.tsx`) that fits whatever shape the card is.
  questRegion: varchar('quest_region', { length: 32 }),
  isTestService: boolean('is_test_service').default(false),
  // When true, the service also surfaces in the «Актуальное» (actual) category
  // in addition to its native category — used to spotlight a new/current
  // service without moving it out of its real category.
  featuredInActual: boolean('featured_in_actual').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

// Upsell links: quest services offered in a modal when the parent (exploration)
// service is added to the cart. Mapping source: SERVICE_ADDONS.md.
export const serviceAddons = pgTable('service_addons', {
  id: uuid('id').defaultRandom().primaryKey(),
  parentServiceId: uuid('parent_service_id').references(() => services.id, { onDelete: 'cascade' }).notNull(),
  addonServiceId: uuid('addon_service_id').references(() => services.id, { onDelete: 'cascade' }).notNull(),
  sortOrder: integer('sort_order').default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const orderStatusEnum = pgEnum('order_status', ['pending', 'paid', 'in_progress', 'completed', 'cancelled', 'refunded']);

export const orders = pgTable('orders', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  // Assigned booster (качер). Nullable — set via "Назначить" in /admin/orders.
  // Forward-ref to `boosters` (defined below) is safe: Drizzle calls the thunk lazily.
  boosterId: uuid('booster_id').references(() => boosters.id, { onDelete: 'set null' }),
  // Commission credited to the booster when this order was completed.
  // NULL = not yet credited; set exactly once (idempotency guard). Independent
  // of revenue accounting — the dashboard still counts full totalPrice.
  boosterEarning: decimal('booster_earning', { precision: 10, scale: 2 }),
  // Toggled by the booster from /portal: «я на аккаунте». Shown to the
  // customer as a badge on their order. No notifications on toggle.
  boosterOnline: boolean('booster_online').notNull().default(false),
  status: orderStatusEnum('status').default('pending'),
  totalPrice: decimal('total_price', { precision: 10, scale: 2 }).notNull(),
  paymentId: varchar('payment_id', { length: 255 }),
  // Acquiring channel chosen at checkout: 'sbp' | 'card' (nullable for legacy rows).
  paymentMethod: varchar('payment_method', { length: 20 }),
  // True for orders created via the admin testing flow (new SBP/card payment test).
  isTestPayment: boolean('is_test_payment').default(false),
  userNotes: text('user_notes'),
  promocode: varchar('promocode', { length: 10 }),
  // Celebration modals («оплата прошла» / «заказ выполнен») are shown to the
  // customer exactly once per order: NULL = event not yet shown, the client
  // watcher acks by setting the timestamp (see /api/user/order-events).
  paidNotifiedAt: timestamp('paid_notified_at', { withTimezone: true }),
  completedNotifiedAt: timestamp('completed_notified_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const orderItems = pgTable('order_items', {
  id: uuid('id').defaultRandom().primaryKey(),
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'cascade' }),
  serviceId: uuid('service_id').references(() => services.id, { onDelete: 'cascade' }),
  quantity: integer('quantity').default(1),
  priceAtPurchase: decimal('price_at_purchase', { precision: 10, scale: 2 }).notNull(),
  startDate: timestamp('start_date', { withTimezone: true }),
  endDate: timestamp('end_date', { withTimezone: true }),
  // 'completed' | 'self' — what the client declared in the quest-addon modal
  // for an exploration service: gating quests already done / will do them
  // themselves. NULL = no declaration (chose quests or no addons exist).
  addonChoice: varchar('addon_choice', { length: 20 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const promocodes = pgTable('promocodes', {
  id: uuid('id').defaultRandom().primaryKey(),
  code: varchar('code', { length: 10 }).notNull().unique(),
  discountPercent: integer('discount_percent').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const promocodeUsage = pgTable('promocode_usage', {
  id: uuid('id').defaultRandom().primaryKey(),
  promocodeId: uuid('promocode_id').references(() => promocodes.id, { onDelete: 'cascade' }).notNull(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  orderId: uuid('order_id').references(() => orders.id, { onDelete: 'cascade' }),
  usedAt: timestamp('used_at', { withTimezone: true }).defaultNow(),
});

export const events = pgTable('events', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  description: text('description'),
  discountPercent: integer('discount_percent').notNull(),
  backgroundUrl: varchar('background_url', { length: 255 }),
  startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
  endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const eventServices = pgTable('event_services', {
  id: uuid('id').defaultRandom().primaryKey(),
  eventId: uuid('event_id').references(() => events.id, { onDelete: 'cascade' }).notNull(),
  serviceId: uuid('service_id').references(() => services.id, { onDelete: 'cascade' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const reviewStatusEnum = pgEnum('review_status', ['pending', 'approved', 'rejected']);

export const reviews = pgTable('reviews', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  rating: decimal('rating', { precision: 2, scale: 1 }).notNull(), // 0.5, 1.0, 1.5, ..., 5.0
  description: text('description').notNull(),
  status: reviewStatusEnum('status').default('pending'),
  // Admin-seeded fake reviews (isFake=true, userId=null) carry their own author
  // identity inline instead of joining `users`. authorAvatarUrl null → the UI
  // renders the first letter of authorName, same as real users with no avatar.
  isFake: boolean('is_fake').notNull().default(false),
  authorName: varchar('author_name', { length: 255 }),
  authorAvatarUrl: varchar('author_avatar_url', { length: 512 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

// NB: cart_items has a unique index on (user_id, service_id) — one line per
// service per user; the sync route inserts with onConflictDoNothing.
export const cartItems = pgTable('cart_items', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  serviceId: uuid('service_id').references(() => services.id, { onDelete: 'cascade' }).notNull(),
  quantity: integer('quantity').notNull().default(1),
  startDate: timestamp('start_date', { withTimezone: true }),
  endDate: timestamp('end_date', { withTimezone: true }),
  // See orderItems.addonChoice — the declaration travels cart → order.
  addonChoice: varchar('addon_choice', { length: 20 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const boosterStatusEnum = pgEnum('booster_status', ['active', 'inactive']);

// Manually-managed roster of boosters (качеры). No login/registration — admins
// add and edit these rows directly from /admin/boosters. Payout fields exist
// because each finished order splits revenue (booster commission vs. house);
// `balance` accumulates the booster's unpaid earnings, paid out off-platform.
export const boosters = pgTable('boosters', {
  id: uuid('id').defaultRandom().primaryKey(),
  // Portal access: links the roster row to a site account (users.role is set
  // to 'booster' on link). NULL = no portal access. The FK is the identity
  // that scopes portal queries; the role only gates the routes.
  userId: uuid('user_id').unique().references(() => users.id, { onDelete: 'set null' }),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  birthDate: timestamp('birth_date', { withTimezone: true }),
  telegramUsername: varchar('telegram_username', { length: 255 }),
  // Самозанятый: ИНН нужен для легального чека/выплаты через «Мой налог».
  inn: varchar('inn', { length: 12 }),
  // Куда платить: номер карты или телефон для СБП (свободная строка).
  payoutDetails: varchar('payout_details', { length: 255 }),
  // Доля качера от заказа в процентах (остальное — проекту). По умолчанию 40%.
  commissionPercent: integer('commission_percent').notNull().default(40),
  // Накопленный, ещё не выплаченный заработок. Decimal хранится как строка.
  balance: decimal('balance', { precision: 10, scale: 2 }).notNull().default('0'),
  status: boosterStatusEnum('status').notNull().default('active'),
  note: text('note'),
  startDate: timestamp('start_date', { withTimezone: true }).defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const boosterDocTypeEnum = pgEnum('booster_doc_type', ['agreement', 'passport']);

// Personal documents (договор + скан паспорта) for each booster. The files
// themselves live in the PRIVATE bucket (`whaleabyss-private`) — never in the
// public one — and are only reachable by streaming through the admin-guarded
// API route. One document of each type per booster; re-upload replaces.
export const boosterDocuments = pgTable('booster_documents', {
  id: uuid('id').defaultRandom().primaryKey(),
  boosterId: uuid('booster_id').notNull().references(() => boosters.id, { onDelete: 'cascade' }),
  docType: boosterDocTypeEnum('doc_type').notNull(),
  // Key inside the private bucket — random suffix, no PII in the key itself.
  s3Key: varchar('s3_key', { length: 512 }).notNull(),
  // Original filename, kept only for the download dialog.
  fileName: varchar('file_name', { length: 255 }).notNull(),
  mimeType: varchar('mime_type', { length: 100 }).notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (t) => [
  unique('booster_documents_booster_doc_type_unique').on(t.boosterId, t.docType),
]);